package com.liberty.common.jfinal;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.liberty.system.model.Account;
import com.liberty.system.model.Currency;
import com.liberty.system.model.Kline;
import com.liberty.system.model.Line;
import com.liberty.system.model.Strategy;
import com.liberty.system.model.Stroke;
/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     com.liberty.common.jfinal.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("kline", "id", Kline.class);
		arp.addMapping("stroke", "id", Stroke.class);
		arp.addMapping("currency", "id", Currency.class);
		arp.addMapping("line", "id", Line.class);
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("strategy", "id", Strategy.class);
	}
}

