package com.liberty.system.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCurrency<T extends BaseCurrency> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Integer id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public T setCode(java.lang.String code) {
		set("code", code);
		return (T)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public T setName(java.lang.String name) {
		set("name", name);
		return (T)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public T setFollowed(java.lang.Boolean followed) {
		set("followed", followed);
		return (T)this;
	}
	
	public java.lang.Boolean getFollowed() {
		return get("followed");
	}

	public T setCurrencyType(java.lang.String currencyType) {
		set("currencyType", currencyType);
		return (T)this;
	}
	
	public java.lang.String getCurrencyType() {
		return getStr("currencyType");
	}

}
