package com.liberty.system.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCentre<T extends BaseCentre> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Integer id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public T setStartDate(java.util.Date startDate) {
		set("startDate", startDate);
		return (T)this;
	}
	
	public java.util.Date getStartDate() {
		return get("startDate");
	}

	public T setEndDate(java.util.Date endDate) {
		set("endDate", endDate);
		return (T)this;
	}
	
	public java.util.Date getEndDate() {
		return get("endDate");
	}

	public T setCentreMax(java.lang.Double centreMax) {
		set("centreMax", centreMax);
		return (T)this;
	}
	
	public java.lang.Double getCentreMax() {
		return getDouble("centreMax");
	}

	public T setCentreMin(java.lang.Double centreMin) {
		set("centreMin", centreMin);
		return (T)this;
	}
	
	public java.lang.Double getCentreMin() {
		return getDouble("centreMin");
	}

	public T setMax(java.lang.Double max) {
		set("max", max);
		return (T)this;
	}
	
	public java.lang.Double getMax() {
		return getDouble("max");
	}

	public T setMin(java.lang.Double min) {
		set("min", min);
		return (T)this;
	}
	
	public java.lang.Double getMin() {
		return getDouble("min");
	}

	public T setCurrencyId(java.lang.Integer currencyId) {
		set("currencyId", currencyId);
		return (T)this;
	}
	
	public java.lang.Integer getCurrencyId() {
		return getInt("currencyId");
	}

}
