package com.liberty.system.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccount<T extends BaseAccount> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Integer id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public T setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
		return (T)this;
	}
	
	public java.lang.String getAccountName() {
		return getStr("accountName");
	}

	public T setPassword(java.lang.String password) {
		set("password", password);
		return (T)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public T setAccountType(java.lang.String accountType) {
		set("accountType", accountType);
		return (T)this;
	}
	
	public java.lang.String getAccountType() {
		return getStr("accountType");
	}

}
