package com.liberty.system.model.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStrategy<T extends BaseStrategy> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Integer id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public T setDescribe(java.lang.String describe) {
		set("describe", describe);
		return (T)this;
	}
	
	public java.lang.String getDescribe() {
		return getStr("describe");
	}

}
