package com.liberty.system.model;

import java.util.List;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.liberty.system.model.base.BaseAccount;
import com.liberty.system.model.base.BaseCurrency;
import com.liberty.system.model.base.BaseStroke;
import com.liberty.system.query.StrokeQueryObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	public static final Account dao = new Account().dao();
	
	public Account getAccountByName(String name) {
		SqlPara sqlPara = getSqlParaFromTemplate(Kv.by("name", name));
		Account account = dao.findFirst(sqlPara);
		return account;
	}
}
