package com.liberty.system.model;

import java.util.List;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.liberty.system.model.base.BaseAccount;
import com.liberty.system.model.base.BaseCentre;
import com.liberty.system.model.base.BaseCurrency;
import com.liberty.system.model.base.BaseStroke;
import com.liberty.system.query.StrokeQueryObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Centre extends BaseCentre<Centre> {
	public static final Centre dao = new Centre().dao();
	
}
