package com.liberty.system.model;

import java.util.List;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.SqlPara;
import com.liberty.system.model.base.BaseStrategy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Strategy extends BaseStrategy<Strategy>{
	public static final Strategy dao = new Strategy().dao();
	
	public List<Strategy> getByCurrency(int currencyId){
		SqlPara sqlPara = getSqlParaFromTemplate(Kv.by("currencyId", currencyId));
		List<Strategy> list = dao.find(sqlPara);
		return list;
	}

	public List<Strategy> getAll() {
		String sql = getSqlFromTemplate();
		List<Strategy> list = dao.find(sql);
		return list;
	}
}
